name: Build project

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install CMake and g++
        run: |
          sudo apt update
          sudo apt install -y cmake g++

      - name: Set up vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          bash vcpkg/bootstrap-vcpkg.sh -disableMetrics

      - name: Install dependencies with vcpkg
        run: |
          vcpkg/vcpkg install crow spdlog nlohmann-json

      - name: Configure CMake
        run: |
          cmake -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake -S . -B build -DCMAKE_CXX_COMPILER=g++
           
      - name: Build the project
        run: |
          cd build
          make

      - name: Upload executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: code_sandbox_linux_x86_64
          path: build/CodeSandbox
